language: node_js
node_js:
  - "8.9"
  - "9.6"
  - "lts/*"
  - "node"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- npm run standard
- npm run test-headless
